const RANGE=(path,label,min,max,step=.01,suffix='')=>({type:'range',path,label,min,max,step,suffix});
const SELECT=(path,label,options)=>({type:'select',path,label,options});
const COLOR=(path,label)=>({type:'color',path,label});
const CHECK=(path,label)=>({type:'check',path,label});

const humanPanels={
  shape:{title:'Corpo',sections:[
    {title:'Geração autônoma',controls:[RANGE('human.autonomy','Autonomia procedural',0,1,.01),RANGE('human.age','Idade',18,85,1,' anos'),SELECT('human.sex','Tipo corporal',[['female','Feminino'],['male','Masculino']])]},
    {title:'Base',controls:[RANGE('human.height','Altura',1.45,2.05,.01,' m'),RANGE('human.bodyMass','Volume corporal',.72,1.35,.01),RANGE('human.muscle','Definição muscular',.75,1.35,.01),RANGE('human.headScale','Escala da cabeça',.88,1.12,.01)]},
    {title:'Silhueta',controls:[RANGE('human.shoulderWidth','Ombros',.78,1.25,.01),RANGE('human.chestWidth','Tórax',.78,1.25,.01),RANGE('human.chestDepth','Profundidade do tórax',.80,1.24,.01),RANGE('human.waistWidth','Cintura',.76,1.30,.01),RANGE('human.hipWidth','Quadril',.78,1.28,.01),RANGE('human.glute','Volume posterior',.78,1.28,.01)]},
    {title:'Proporções',controls:[RANGE('human.torsoLength','Tronco',.84,1.18,.01),RANGE('human.legLength','Pernas',.86,1.16,.01),RANGE('human.armLength','Braços',.88,1.14,.01),RANGE('human.neckThickness','Pescoço',.78,1.25,.01),RANGE('human.handScale','Escala das mãos',.78,1.24,.01),RANGE('human.fingerLength','Comprimento dos dedos',.78,1.25,.01)]}
  ]},
  face:{title:'Rosto',sections:[
    {title:'Crânio e mandíbula',controls:[RANGE('human.faceWidth','Largura facial',.84,1.16,.01),RANGE('human.headDepth','Profundidade craniana',.86,1.16,.01),RANGE('human.foreheadHeight','Testa',.82,1.18,.01),RANGE('human.cheekbones','Maçãs do rosto',.82,1.18,.01),RANGE('human.jawWidth','Mandíbula',.78,1.20,.01),RANGE('human.chinSize','Queixo',.78,1.24,.01),RANGE('human.earScale','Orelhas',.80,1.25,.01)]},
    {title:'Olhos e sobrancelhas',controls:[RANGE('human.eyeScale','Tamanho dos olhos',.82,1.22,.01),RANGE('human.eyeSpacing','Espaçamento',.84,1.18,.01),RANGE('human.eyelidOpen','Abertura palpebral',.72,1.18,.01),RANGE('human.browHeight','Altura da sobrancelha',.80,1.20,.01),RANGE('human.browThickness','Espessura da sobrancelha',.60,1.45,.01)]},
    {title:'Nariz e boca',controls:[RANGE('human.noseScale','Comprimento do nariz',.78,1.24,.01),RANGE('human.noseWidth','Largura do nariz',.76,1.24,.01),RANGE('human.noseBridge','Ponte nasal',.72,1.28,.01),RANGE('human.mouthWidth','Largura da boca',.78,1.24,.01),RANGE('human.lipFullness','Volume labial',.62,1.42,.01),RANGE('human.asymmetry','Assimetria natural',0,.18,.005)]},
    {title:'Expressão',controls:[SELECT('human.expression','Preset',[['neutral','Neutra'],['smile','Sorriso'],['serious','Séria'],['surprised','Surpresa'],['angry','Irritada']]),RANGE('human.smile','Sorriso manual',0,1,.01),RANGE('human.jawOpen','Abertura da boca',0,1,.01),RANGE('human.browRaise','Sobrancelhas',-.6,.8,.01),RANGE('human.squint','Semicerrar olhos',0,1,.01),RANGE('human.blinkSpeed','Frequência de piscar',.25,2.5,.05)]},
    {title:'Pele',controls:[RANGE('human.skinRoughness','Rugosidade',.28,.72,.01),RANGE('human.skinDetail','Microdetalhes',0,1,.01),COLOR('human.skin','Pele'),COLOR('human.eyes','Íris'),COLOR('human.lipColor','Lábios')]}
  ]},
  hair:{title:'Cabelo',sections:[{title:'Estilo',cards:{path:'human.hairStyle',options:[['long-side','Longo','Guias procedurais longas'],['bob','Bob','Volume médio'],['short','Curto','Cap compacto']]}},{title:'Geometria',controls:[RANGE('human.hairLength','Comprimento',.55,1.55,.01),RANGE('human.hairDensity','Densidade',.55,1.45,.01)]},{title:'Material',controls:[COLOR('human.hair','Cor do cabelo')]}]},
  clothing:{title:'Roupa',sections:[{title:'Conjunto',cards:{path:'human.outfit',options:[['casual','Casual','Malha e calça'],['jacket','Jaqueta','Casca estruturada'],['formal','Formal','Silhueta de casaco']]}},{title:'Cores',controls:[COLOR('human.topColor','Parte superior'),COLOR('human.bottomColor','Parte inferior')]}]},
  materials:{title:'Materiais',sections:[
    {title:'Pele',controls:[RANGE('human.skinRoughness','Rugosidade',.28,.72,.01),RANGE('human.skinDetail','Microdetalhes',0,1,.01),RANGE('human.subsurface','Profundidade de pele',0,1,.01),COLOR('human.skin','Pele')]},
    {title:'Olhos',controls:[RANGE('human.eyeWetness','Brilho/córnea',0,1,.01),RANGE('human.tearline','Linha lacrimal',0,1,.01),COLOR('human.eyes','Íris')]},
    {title:'Boca e cabelo',controls:[RANGE('human.oralDetail','Detalhe oral',0,1,.01),COLOR('human.lipColor','Lábios'),COLOR('human.hair','Cabelo')]},
    {title:'Roupa',controls:[COLOR('human.topColor','Roupa superior'),COLOR('human.bottomColor','Roupa inferior')]}
  ]},
  animation:{title:'Rig & Movimento',sections:[
    {title:'Pose e esqueleto',controls:[SELECT('human.pose','Pose base',[['relaxed','Relaxada'],['hero','Heroica'],['contrapposto','Contrapposto'],['apose','A-Pose'],['tpose','T-Pose']]),CHECK('human.rigVisible','Exibir esqueleto')]},
    {title:'Mãos articuladas',controls:[SELECT('human.handPose','Pose das mãos',[['open','Aberta'],['relaxed','Relaxada'],['fist','Punho'],['grip','Pegada'],['point','Apontar']]),RANGE('human.handCurlStrength','Força da pose',0,1.2,.01),RANGE('human.handScale','Escala das mãos',.78,1.24,.01),RANGE('human.fingerLength','Comprimento dos dedos',.78,1.25,.01)]},
    {title:'Animação procedural',controls:[SELECT('human.animation','Movimento',[['idle','Idle vivo'],['breathing','Respiração'],['walk','Caminhada'],['run','Corrida'],['off','Desligado']]),RANGE('human.animationSpeed','Velocidade',.25,2.5,.05),RANGE('human.animationStrength','Intensidade',0,1,.01)]},
    {title:'IK automático',controls:[CHECK('human.ikEnabled','Ativar IK mãos/pés'),RANGE('human.ikWeight','Peso do IK',0,1,.01),RANGE('human.ikReach','Alcance procedural',0,1,.01)]},
    {title:'Deformação corretiva',controls:[RANGE('human.correctiveStrength','Preservação de volume',0,1,.01)]},
    {title:'Compatibilidade',controls:[SELECT('human.retargetProfile','Perfil de retarget',[['engine-person-humanoid','Engine Person Humanoid']])]}
  ]},
  environment:{title:'Ambiente',sections:[{title:'Iluminação',controls:[RANGE('environment.timeOfDay','Hora',0,24,.1,' h'),RANGE('environment.exposure','Exposição',.45,1.8,.01),COLOR('environment.ground','Solo')]}]}
};

const cityPanel={title:'Mundo Procedural',sections:[
  {title:'Época e linguagem',controls:[SELECT('city.era','Estilo de mundo',[['modern','Moderno'],['medieval','Medieval'],['hybrid','Híbrido']]),RANGE('city.organicLayout','Organicidade das ruas',0,1,.01),RANGE('city.fortification','Fortificações',0,1,.01),RANGE('city.towerChance','Torres',0,1,.01),RANGE('city.marketRatio','Praças/mercados',0,.50,.01),RANGE('city.timberRatio','Madeira aparente',0,1,.01)]},
  {title:'Plano urbano',controls:[RANGE('city.blocksX','Blocos X',3,12,1),RANGE('city.blocksZ','Blocos Z',3,12,1),RANGE('city.streetWidth','Largura das ruas',.08,.35,.01),RANGE('city.parcelSubdivision','Subdivisão de lotes',0,1,.01),RANGE('city.commercialMix','Mistura comercial',0,1,.01),RANGE('city.greenRatio','Áreas verdes',0,.42,.01)]},
  {title:'Ocupação e skyline',controls:[RANGE('city.density','Densidade',.18,1,.01),RANGE('city.minFloors','Mín. pavimentos',1,8,1),RANGE('city.maxFloors','Máx. pavimentos',2,28,1),RANGE('city.variation','Variação volumétrica',0,1,.01),RANGE('city.facadeHue','Família de cor',0,1,.01)]}
]};
const projectPanel={title:'Projeto',sections:[{title:'Engine Person',html:'<p style="font-size:11px;color:#9ba8b8;line-height:1.55;margin:0">Arquitetura local-first e determinística. Personagens possuem geração autônoma, materiais especializados, auto-skinning, rig humano completo com dedos, IK, deformações corretivas, expressões procedurais e retarget. Mundos aceitam linguagem moderna, medieval ou híbrida.</p>'}]};
function formatValue(c,v){if(c.step>=1)return`${Math.round(v)}${c.suffix??''}`;const digits=c.step<.01?3:c.step<.1?2:1;return`${Number(v).toFixed(digits)}${c.suffix??''}`;}
export class InspectorUI{
  constructor(store,onChange){this.store=store;this.onChange=onChange;this.title=document.querySelector('#panelTitle');this.content=document.querySelector('#panelContent');}
  render(mode=this.store.get('mode'),tool=this.store.get('activeTool')){const schema=mode==='city'?cityPanel:mode==='project'?projectPanel:(humanPanels[tool]??humanPanels.shape);this.title.textContent=schema.title;this.content.innerHTML='';schema.sections.forEach(section=>{const el=document.createElement('section');el.className='section';el.innerHTML=`<h3>${section.title}</h3>`;if(section.html)el.insertAdjacentHTML('beforeend',section.html);if(section.controls)section.controls.forEach(c=>el.appendChild(this.control(c)));if(section.cards)el.appendChild(this.cards(section.cards));this.content.appendChild(el);});}
  control(c){const wrap=document.createElement('div');wrap.className='control';const value=this.store.get(c.path);const label=document.createElement('label');label.textContent=c.label;wrap.appendChild(label);if(c.type==='range'){const output=document.createElement('output');output.textContent=formatValue(c,value);const input=document.createElement('input');input.type='range';input.min=c.min;input.max=c.max;input.step=c.step;input.value=value;input.addEventListener('input',()=>{const next=Number(input.value);output.textContent=formatValue(c,next);this.store.set(c.path,next);this.onChange?.(c.path);});wrap.append(output,input);}else if(c.type==='select'){const input=document.createElement('select');c.options.forEach(([v,t])=>input.add(new Option(t,v)));input.value=value;input.addEventListener('change',()=>{this.store.set(c.path,input.value);this.onChange?.(c.path);});wrap.appendChild(input);}else if(c.type==='color'){const input=document.createElement('input');input.type='color';input.value=value;input.addEventListener('input',()=>{this.store.set(c.path,input.value);this.onChange?.(c.path);});wrap.appendChild(input);}else if(c.type==='check'){const input=document.createElement('input');input.type='checkbox';input.checked=!!value;input.addEventListener('change',()=>{this.store.set(c.path,input.checked);this.onChange?.(c.path);});wrap.appendChild(input);}return wrap;}
  cards(schema){const grid=document.createElement('div');grid.className='card-grid';schema.options.forEach(([value,title,desc])=>{const button=document.createElement('button');button.className=`choice-card ${this.store.get(schema.path)===value?'active':''}`;button.innerHTML=`<strong>${title}</strong><span>${desc}</span>`;button.addEventListener('click',()=>{this.store.set(schema.path,value);this.onChange?.(schema.path);this.render();});grid.appendChild(button);});return grid;}
}
