import { computeSupermarketLayout } from '../generators/supermarket.js';

const RANGE=(path,label,min,max,step=.01,suffix='')=>({type:'range',path,label,min,max,step,suffix});
const CHECK=(path,label)=>({type:'check',path,label});
const STEPPER=(path,label,min,max,step=1)=>({type:'stepper',path,label,min,max,step});
const SECTOR_TYPES=[['sales','Área de vendas','#cfe6ff'],['checkout','Frente de caixa','#ffd9a8'],['stock','Depósito','#d8d1ff'],['parking','Estacionamento','#c9d0d6'],['service','Atendimento / serviços','#cfead8'],['office','Administrativo','#ffe7b8'],['receiving','Recebimento','#d6e1c3'],['custom','Outro setor','#d9dde2']];
const schema={title:'Gôndolas de Supermercado',sections:[
  {title:'Planta da loja',custom:'plan'},
  {title:'Dimensionamento',controls:[STEPPER('supermarket.gondolaRows','Fileiras de gôndolas',1,60,1),STEPPER('supermarket.modules','Módulos por gôndola',1,60,1),STEPPER('supermarket.shelves','Prateleiras',1,12,1)]},
  {title:'Estrutura',controls:[RANGE('supermarket.moduleWidth','Largura do módulo',.70,1.40,.05,' m'),RANGE('supermarket.depth','Profundidade',.45,1.10,.05,' m'),RANGE('supermarket.height','Altura',1.20,2.40,.05,' m'),RANGE('supermarket.aisleWidth','Largura do corredor',1.10,4,.05,' m'),CHECK('supermarket.doubleSided','Gôndolas dupla face'),CHECK('supermarket.backPanel','Fundo / painel traseiro')]},
  {title:'Terminais e laterais',controls:[CHECK('supermarket.endcaps','Terminais de gôndola'),CHECK('supermarket.wallGondolas','Laterais / paredes com gôndolas')]},
  {title:'Operação de loja',controls:[RANGE('supermarket.productFill','Ocupação de produtos',0,1,.01),STEPPER('supermarket.promoTables','Bancadas promocionais',0,20,1),STEPPER('supermarket.checkouts','Checkouts / caixas',0,30,1)]},
  {title:'Leitura do módulo',html:'<p class="warehouse-dimension-hint">O Mapa 2D é a planta baixa do mesmo modelo 3D: piso, paredes, divisórias, setores, gôndolas, bancadas e caixas. Arraste equipamentos no 2D e o 3D acompanha.</p>'}
]};
function format(c,v){if(c.step>=1)return String(Math.round(v));const digits=c.step<.1?2:1;return`${Number(v).toFixed(digits)}${c.suffix??''}`;}

export class SupermarketPanelUI{
  constructor(store,onChange){this.store=store;this.onChange=onChange;this.title=document.querySelector('#panelTitle');this.content=document.querySelector('#panelContent');this.planMode='area';this.activeSectorId=null;this.commitTimer=null;}
  ensurePlan(){if(!this.store.state.supermarket.plan)this.store.state.supermarket.plan={cols:16,rows:12,cellSize:1.5,targetArea:432,showWalls:true,wallHeight:2.8,wallThickness:.12,activeCells:[],dividers:[],sectors:[],objectPlacements:{}};const p=this.store.state.supermarket.plan;p.cols=Math.max(4,Math.min(160,Math.round(p.cols??16)));p.rows=Math.max(4,Math.min(160,Math.round(p.rows??12)));p.cellSize=Math.max(.4,Math.min(10,Number(p.cellSize??1.5)));p.targetArea=Number(p.targetArea??p.cols*p.rows*p.cellSize*p.cellSize);p.showWalls=p.showWalls!==false;p.wallHeight=Number(p.wallHeight??2.8);p.wallThickness=Number(p.wallThickness??.12);if(!Array.isArray(p.activeCells))p.activeCells=[];if(!Array.isArray(p.dividers))p.dividers=[];if(!Array.isArray(p.sectors))p.sectors=[];if(!p.objectPlacements||typeof p.objectPlacements!=='object')p.objectPlacements={};return p;}
  commit(path='supermarket.plan',delay=90){clearTimeout(this.commitTimer);this.commitTimer=setTimeout(()=>this.onChange?.(path),delay);}
  render(){this.ensurePlan();this.title.textContent=schema.title;this.content.innerHTML='';for(const section of schema.sections){const el=document.createElement('section');el.className='section';el.innerHTML=`<h3>${section.title}</h3>`;if(section.html)el.insertAdjacentHTML('beforeend',section.html);if(section.custom==='plan')el.appendChild(this.planEditor());for(const c of section.controls??[])el.appendChild(this.control(c));this.content.appendChild(el);}}
  planEditor(){const p=this.ensurePlan(),wrap=document.createElement('div'),hint=document.createElement('p');hint.className='warehouse-dimension-hint';hint.textContent='A planta baixa 2D e o 3D usam o mesmo layout. Desenhe áreas, setores e divisórias no mapa, ou arraste os equipamentos.';wrap.appendChild(hint);
    const area=document.createElement('div');area.style.cssText='display:grid;grid-template-columns:1fr 90px;gap:7px;margin-bottom:9px';const input=document.createElement('input');input.type='number';input.min='25';input.max='500000';input.step='25';input.value=Math.round(p.targetArea);input.style.cssText='width:100%;border:1px solid rgba(255,255,255,.09);border-radius:9px;background:#111722;color:#edf2f7;padding:9px';const apply=document.createElement('button');apply.className='warehouse-toggle-btn';apply.textContent='Aplicar m²';apply.onclick=()=>this.applyTargetArea(Number(input.value));const lab=document.createElement('small');lab.textContent='Área alvo aproximada (m²)';lab.style.cssText='grid-column:1/3;color:#9ba8b8';area.append(lab,input,apply);wrap.appendChild(area);
    const map=document.createElement('button');map.className='primary';map.textContent='Abrir Planta Baixa 2D';map.style.marginBottom='9px';map.onclick=()=>this.openFloorplanModal();wrap.appendChild(map);
    const wt=document.createElement('div');wt.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:9px';for(const [v,l] of [[true,'Mostrar paredes'],[false,'Ocultar paredes']]){const b=document.createElement('button');b.className=`warehouse-toggle-btn ${p.showWalls===v?'active':''}`;b.textContent=l;b.onclick=()=>{p.showWalls=v;this.onChange?.('supermarket.plan.showWalls');this.render();};wt.appendChild(b);}wrap.appendChild(wt);
    const dims=document.createElement('div');dims.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:8px';dims.append(this.miniStepper('Colunas',p.cols,4,160,v=>{p.cols=v;this.cropPlan();p.targetArea=p.cols*p.rows*p.cellSize*p.cellSize;this.onChange?.('supermarket.plan.cols');this.render();}),this.miniStepper('Linhas',p.rows,4,160,v=>{p.rows=v;this.cropPlan();p.targetArea=p.cols*p.rows*p.cellSize*p.cellSize;this.onChange?.('supermarket.plan.rows');this.render();}));wrap.appendChild(dims);wrap.append(this.compactRange('Tamanho da célula',p.cellSize,.5,10,.1,' m',v=>{p.cellSize=v;p.targetArea=p.cols*p.rows*v*v;this.commit('supermarket.plan.cellSize');}),this.compactRange('Altura das paredes',p.wallHeight,1.5,5,.1,' m',v=>{p.wallHeight=v;this.commit('supermarket.plan.wallHeight');}));return wrap;}
  applyTargetArea(area){const p=this.ensurePlan();if(!Number.isFinite(area)||area<25)return;const ratio=Math.max(.2,Math.min(5,p.cols/Math.max(1,p.rows)));let cells=Math.ceil(area/(p.cellSize*p.cellSize)),rows=Math.max(4,Math.round(Math.sqrt(cells/ratio))),cols=Math.max(4,Math.ceil(cells/rows));if(cols>160||rows>160){const needed=Math.sqrt(area/(160*160));p.cellSize=Math.min(10,Math.max(p.cellSize,Math.ceil(needed*10)/10));cells=Math.ceil(area/(p.cellSize*p.cellSize));rows=Math.max(4,Math.min(160,Math.round(Math.sqrt(cells/ratio))));cols=Math.max(4,Math.min(160,Math.ceil(cells/rows)));}p.cols=Math.min(160,cols);p.rows=Math.min(160,rows);p.targetArea=area;p.activeCells=[];p.dividers=[];p.sectors=[];p.objectPlacements={};this.onChange?.('supermarket.plan');this.render();}
  cropPlan(){const p=this.ensurePlan();p.activeCells=p.activeCells.filter(k=>{const [r,c]=k.split(',').map(Number);return r<p.rows&&c<p.cols;});p.dividers=p.dividers.filter(k=>{const [r,c]=k.split(',').map(Number);return r<p.rows&&c<p.cols;});for(const s of p.sectors)s.cells=(s.cells??[]).filter(k=>{const [r,c]=k.split(',').map(Number);return r<p.rows&&c<p.cols;});}

  openFloorplanModal(){const p=this.ensurePlan();document.querySelector('#supermarketFloorplanModal')?.remove();const overlay=document.createElement('div');overlay.id='supermarketFloorplanModal';overlay.className='floorplan-overlay';const modal=document.createElement('div');modal.className='floorplan-modal';const side=document.createElement('aside');side.className='floorplan-side';const workspace=document.createElement('main');workspace.className='floorplan-workspace';modal.append(side,workspace);overlay.appendChild(modal);document.body.appendChild(overlay);
    side.innerHTML='<div class="floorplan-kicker">PLANTA BAIXA OPERACIONAL</div><h2>Editor 2D da loja</h2><p class="floorplan-help">Esta é a projeção do mesmo cenário 3D. Edite a planta ou mova equipamentos; a renderização 3D é atualizada em lote.</p>';
    const tools=document.createElement('div');tools.className='floorplan-tools';side.appendChild(tools);const modes=[['select','Selecionar / mover'],['area','Desenhar área'],['sector','Pintar setor'],['h','Divisória H'],['v','Divisória V']];let mode='select';const renderToolState=()=>[...tools.children].forEach((b,i)=>b.classList.toggle('active',modes[i][0]===mode));for(const [v,l] of modes){const b=document.createElement('button');b.className='warehouse-toggle-btn';b.textContent=l;b.onclick=()=>{mode=v;renderToolState();};tools.appendChild(b);}renderToolState();
    const sectorBox=document.createElement('div');sectorBox.className='floorplan-sector-box';side.appendChild(sectorBox);const type=document.createElement('select'),name=document.createElement('input'),parking=document.createElement('input'),add=document.createElement('button');for(const [v,l] of SECTOR_TYPES){const o=document.createElement('option');o.value=v;o.textContent=l;type.appendChild(o);}name.placeholder='Nome do setor';parking.type='number';parking.min='0';parking.placeholder='Vagas';parking.style.display='none';type.onchange=()=>parking.style.display=type.value==='parking'?'block':'none';add.className='primary';add.textContent='Adicionar setor';sectorBox.append(type,name,parking,add);const sectorList=document.createElement('div');sectorList.className='floorplan-sector-list';side.appendChild(sectorList);
    const renderSectorList=()=>{sectorList.innerHTML='';for(const s of p.sectors){const b=document.createElement('button');b.className=`floorplan-sector-item ${this.activeSectorId===s.id?'active':''}`;b.innerHTML=`<i style="background:${s.color}"></i><span>${s.name}${s.type==='parking'?` · ${s.parkingSpaces||0} vagas`:''}</span>`;b.onclick=()=>{this.activeSectorId=s.id;mode='sector';renderToolState();renderSectorList();};sectorList.appendChild(b);}};add.onclick=()=>{const spec=SECTOR_TYPES.find(x=>x[0]===type.value),s={id:`S${Date.now()}`,type:type.value,name:name.value.trim()||spec[1],color:spec[2],parkingSpaces:type.value==='parking'?Math.max(0,Number(parking.value||0)):0,cells:[]};p.sectors.push(s);this.activeSectorId=s.id;mode='sector';renderToolState();renderSectorList();draw();this.commit();};renderSectorList();
    const selectedInfo=document.createElement('div');selectedInfo.className='floorplan-selection';selectedInfo.textContent='Nenhum equipamento selecionado';side.appendChild(selectedInfo);const rotate=document.createElement('button');rotate.className='ghost-btn';rotate.textContent='Girar 90°';rotate.disabled=true;side.appendChild(rotate);const reset=document.createElement('button');reset.className='ghost-btn';reset.textContent='Resetar posições automáticas';reset.onclick=()=>{p.objectPlacements={};selectedId=null;draw();this.commit('supermarket.plan.objectPlacements',0);};side.appendChild(reset);
    const top=document.createElement('div');top.className='floorplan-top';const meta=document.createElement('div');const close=document.createElement('button');close.className='ghost-btn';close.textContent='Concluir';close.onclick=()=>{overlay.remove();this.onChange?.('supermarket.plan');};top.append(meta,close);const stage=document.createElement('div');stage.className='floorplan-stage';workspace.append(top,stage);
    let selectedId=null,painting=false,lastKey='';
    const draw=()=>{const layout=computeSupermarketLayout(this.store.state.supermarket);meta.textContent=`${p.cols} × ${p.rows} células · ${p.cellSize.toFixed(1)} m/célula · ${Math.round(p.cols*p.rows*p.cellSize*p.cellSize)} m² brutos`;stage.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${layout.width} ${layout.depth}`);svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.classList.add('floorplan-svg');stage.appendChild(svg);const ox=-layout.width/2,oz=-layout.depth/2,custom=new Set(p.activeCells),isActive=(r,c)=>custom.size?custom.has(`${r},${c}`):true,sectorMap=new Map();for(const s of p.sectors)for(const k of s.cells??[])sectorMap.set(k,s);
      const worldToSvg=(x,z)=>[x-ox,z-oz];const svgToWorld=(clientX,clientY)=>{const pt=svg.createSVGPoint();pt.x=clientX;pt.y=clientY;const m=svg.getScreenCTM();const q=pt.matrixTransform(m.inverse());return {x:q.x+ox,z:q.y+oz};};
      for(let r=0;r<p.rows;r++)for(let c=0;c<p.cols;c++){const key=`${r},${c}`,active=isActive(r,c),x=c*p.cellSize,y=r*p.cellSize,sector=sectorMap.get(key),rect=document.createElementNS(svg.namespaceURI,'rect');rect.setAttribute('x',x);rect.setAttribute('y',y);rect.setAttribute('width',p.cellSize);rect.setAttribute('height',p.cellSize);rect.setAttribute('class',`fp-cell ${active?'active':'inactive'}`);if(sector)rect.style.fill=sector.color;const applyCell=()=>{if(key===lastKey)return;lastKey=key;if(mode==='area'){let set=new Set(p.activeCells);if(set.size===0){for(let rr=0;rr<p.rows;rr++)for(let cc=0;cc<p.cols;cc++)set.add(`${rr},${cc}`);}set.has(key)?set.delete(key):set.add(key);p.activeCells=[...set];rect.setAttribute('class',`fp-cell ${set.has(key)?'active':'inactive'}`);this.commit();}else if(mode==='sector'&&active){const s=p.sectors.find(s=>s.id===this.activeSectorId);if(!s)return;for(const other of p.sectors)other.cells=(other.cells??[]).filter(k=>k!==key);s.cells=[...new Set([...(s.cells??[]),key])];rect.style.fill=s.color;this.commit();}else if((mode==='h'||mode==='v')&&active){const d=`${key},${mode}`,set=new Set(p.dividers);set.has(d)?set.delete(d):set.add(d);p.dividers=[...set];this.commit();draw();}};rect.addEventListener('pointerdown',e=>{if(mode==='select')return;painting=true;lastKey='';rect.setPointerCapture?.(e.pointerId);applyCell();});rect.addEventListener('pointerenter',()=>{if(painting)applyCell();});svg.appendChild(rect);}
      window.addEventListener('pointerup',()=>{painting=false;lastKey='';},{once:true});
      for(let r=0;r<p.rows;r++)for(let c=0;c<p.cols;c++){if(!isActive(r,c)||!p.showWalls)continue;const x=c*p.cellSize,y=r*p.cellSize,active=(rr,cc)=>rr>=0&&rr<p.rows&&cc>=0&&cc<p.cols&&isActive(rr,cc);const line=(x1,y1,x2,y2,cls='fp-wall')=>{const l=document.createElementNS(svg.namespaceURI,'line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);l.setAttribute('class',cls);svg.appendChild(l);};if(!active(r-1,c))line(x,y,x+p.cellSize,y);if(!active(r+1,c))line(x,y+p.cellSize,x+p.cellSize,y+p.cellSize);if(!active(r,c-1))line(x,y,x,y+p.cellSize);if(!active(r,c+1))line(x+p.cellSize,y,x+p.cellSize,y+p.cellSize);if(p.dividers.includes(`${r},${c},h`))line(x,y+p.cellSize/2,x+p.cellSize,y+p.cellSize/2,'fp-divider');if(p.dividers.includes(`${r},${c},v`))line(x+p.cellSize/2,y,x+p.cellSize/2,y+p.cellSize,'fp-divider');}
      for(const o of layout.objects){const [cx,cy]=worldToSvg(o.x,o.z),g=document.createElementNS(svg.namespaceURI,'g');g.setAttribute('class',`fp-object ${o.type} ${selectedId===o.id?'selected':''}`);g.dataset.id=o.id;g.setAttribute('transform',`translate(${cx} ${cy}) rotate(${(o.rotation||0)*180/Math.PI})`);const rect=document.createElementNS(svg.namespaceURI,'rect');rect.setAttribute('x',-o.width/2);rect.setAttribute('y',-o.depth/2);rect.setAttribute('width',o.width);rect.setAttribute('height',o.depth);rect.setAttribute('rx',Math.min(.12,o.depth*.2));const label=document.createElementNS(svg.namespaceURI,'text');label.setAttribute('x',0);label.setAttribute('y',.08);label.setAttribute('text-anchor','middle');label.textContent=o.type==='gondola'?`G${o.row+1}`:o.type==='checkout'?`CX${o.index+1}`:o.type==='promo'?'BANCADA':'LATERAL';g.append(rect,label);let drag=null;g.addEventListener('pointerdown',e=>{if(mode!=='select')return;e.stopPropagation();selectedId=o.id;rotate.disabled=false;selectedInfo.textContent=`${label.textContent} · arraste para mover`;drag={pointer:e.pointerId};g.setPointerCapture(e.pointerId);g.classList.add('selected');});g.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;const w=svgToWorld(e.clientX,e.clientY),sx=w.x-ox,sy=w.z-oz;g.setAttribute('transform',`translate(${sx} ${sy}) rotate(${(o.rotation||0)*180/Math.PI})`);drag.world=w;});g.addEventListener('pointerup',e=>{if(!drag)return;const w=drag.world||svgToWorld(e.clientX,e.clientY),snap=p.cellSize*.25,x=Math.round(w.x/snap)*snap,z=Math.round(w.z/snap)*snap;p.objectPlacements[o.id]={x,z,rotation:o.rotation||0};drag=null;this.onChange?.('supermarket.plan.objectPlacements');draw();});svg.appendChild(g);}
      rotate.onclick=()=>{if(!selectedId)return;const obj=layout.objects.find(o=>o.id===selectedId);if(!obj)return;const current=p.objectPlacements[selectedId]??{x:obj.x,z:obj.z,rotation:obj.rotation||0};current.rotation=((current.rotation||0)+Math.PI/2)%(Math.PI*2);p.objectPlacements[selectedId]=current;this.onChange?.('supermarket.plan.objectPlacements');draw();};
    };draw();
  }

  miniStepper(label,value,min,max,onSet){const w=document.createElement('div');w.style.display='grid';w.style.gridTemplateColumns='28px 1fr 28px';w.style.gap='4px';const t=document.createElement('small');t.textContent=label;t.style.cssText='grid-column:1/4;color:#9ba8b8';const m=document.createElement('button'),o=document.createElement('output'),p=document.createElement('button');m.className=p.className='warehouse-stepper-btn';m.textContent='−';p.textContent='+';o.className='warehouse-stepper-value';o.textContent=value;m.onclick=()=>onSet(Math.max(min,value-1));p.onclick=()=>onSet(Math.min(max,value+1));w.append(t,m,o,p);return w;}
  compactRange(label,value,min,max,step,suffix,onSet){const w=document.createElement('div');w.className='control';const l=document.createElement('label'),o=document.createElement('output'),i=document.createElement('input');l.textContent=label;o.textContent=`${Number(value).toFixed(1)}${suffix}`;i.type='range';i.min=min;i.max=max;i.step=step;i.value=value;i.oninput=()=>{const v=Number(i.value);o.textContent=`${v.toFixed(1)}${suffix}`;onSet(v);};w.append(l,o,i);return w;}
  control(c){const wrap=document.createElement('div');wrap.className=`control${c.type==='stepper'?' warehouse-stepper-control':''}`;const value=this.store.get(c.path),label=document.createElement('label');label.textContent=c.label;wrap.appendChild(label);if(c.type==='stepper'){const ctr=document.createElement('div');ctr.className='warehouse-stepper';const minus=document.createElement('button'),plus=document.createElement('button'),out=document.createElement('output');minus.className=plus.className='warehouse-stepper-btn';minus.textContent='−';plus.textContent='+';out.className='warehouse-stepper-value';out.textContent=format(c,value);const apply=d=>{const cur=Number(this.store.get(c.path)),next=Math.max(c.min,Math.min(c.max,cur+d));if(next===cur)return;this.store.set(c.path,next);out.textContent=format(c,next);this.onChange?.(c.path);};minus.onclick=()=>apply(-c.step);plus.onclick=()=>apply(c.step);ctr.append(minus,out,plus);wrap.appendChild(ctr);}else if(c.type==='range'){const out=document.createElement('output'),input=document.createElement('input');out.textContent=format(c,value);input.type='range';input.min=c.min;input.max=c.max;input.step=c.step;input.value=value;input.oninput=()=>{const next=Number(input.value);out.textContent=format(c,next);this.store.set(c.path,next,true);this.commit(c.path);};wrap.append(out,input);}else if(c.type==='check'){const input=document.createElement('input');input.type='checkbox';input.checked=!!value;input.onchange=()=>{this.store.set(c.path,input.checked,true);this.onChange?.(c.path);};wrap.appendChild(input);}return wrap;}
}
