import * as THREE from 'three';
import { mulberry32 } from '../core/state.js';

const mat=(color,rough=.9,metal=.02)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});
const STONE='#7b7770',STONE_DARK='#57534d',ROOF='#4e342e',WOOD='#65482e',GRASS='#43533a',WATER='#274d5f',PATH='#7b6c55',FLOWER=['#8a5368','#d0b45e','#7a6fa8','#b76552'];
function box(w,h,d,m,x=0,y=0,z=0){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;return o;}
function cyl(r,h,m,x=0,y=0,z=0,seg=12){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;return o;}
function battlements(g,w,d,y,m){const mer=.22;for(let x=-w/2+.18;x<w/2;x+=.42){g.add(box(.22,.22,.28,m,x,y,-d/2));g.add(box(.22,.22,.28,m,x,y,d/2));}for(let z=-d/2+.18;z<d/2;z+=.42){g.add(box(.28,.22,.22,m,-w/2,y,z));g.add(box(.28,.22,.22,m,w/2,y,z));}}
function tower(r,h,m,x,z,round=true){const g=new THREE.Group();g.position.set(x,0,z);const body=round?cyl(r,h,m,0,h/2,0,14):box(r*1.75,h,r*1.75,m,0,h/2,0);g.add(body);const top=round?new THREE.Mesh(new THREE.CylinderGeometry(r*1.05,r*1.05,.28,14),m):box(r*1.9,.28,r*1.9,m,0,h+.08,0);top.position.y=h+.08;g.add(top);for(let a=0;a<8;a++){const ang=a*Math.PI/4;g.add(box(.22,.24,.22,m,Math.cos(ang)*r*.83,h+.28,Math.sin(ang)*r*.83));}return g;}
function createKeep(c){const g=new THREE.Group(),m=mat(STONE,.96),dark=mat(STONE_DARK,.98);const w=c.keepWidth,d=c.keepDepth,h=c.keepHeight;g.add(box(w,h,d,m,0,h/2,0));battlements(g,w,d,h+.11,m);for(const sx of[-1,1])for(const sz of[-1,1])g.add(tower(.58,h*1.08,dark,sx*w*.42,sz*d*.42,c.towerStyle==='round'));const door=box(.65,1.0,.12,mat(WOOD,.92),0,.5,d/2+.07);g.add(door);return g;}
function wallSegment(w,h,d,m,x,z,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;g.add(box(w,h,d,m,0,h/2,0));for(let p=-w/2+.2;p<w/2;p+=.42)g.add(box(.22,.24,d*1.25,m,p,h+.12,0));return g;}
function createWalls(c){const g=new THREE.Group(),m=mat(STONE_DARK,.98);const w=c.outerWidth,d=c.outerDepth,h=c.wallHeight,t=.34;g.add(wallSegment(w,h,t,m,0,-d/2));g.add(wallSegment(w,h,t,m,0,d/2));g.add(wallSegment(d,h,t,m,-w/2,0,Math.PI/2));g.add(wallSegment(d,h,t,m,w/2,0,Math.PI/2));for(const sx of[-1,1])for(const sz of[-1,1])g.add(tower(.62,h*1.45,m,sx*w/2,sz*d/2,c.towerStyle==='round'));const gateGap=1.25;g.add(box(gateGap,h*.75,t*1.2,mat('#201914',.98),0,h*.375,d/2+.02));return g;}
function createMoat(c){const g=new THREE.Group();if(!c.moat)return g;const outerW=c.outerWidth+2.3,outerD=c.outerDepth+2.3;const water=box(outerW,.10,outerD,mat(WATER,.35,.1),0,.02,0);g.add(water);g.add(box(c.outerWidth+.55,.14,c.outerDepth+.55,mat(GRASS,.98),0,.09,0));const bridge=box(c.bridgeWidth,.18,2.5,mat(WOOD,.9),0,.18,c.outerDepth/2+1.05);g.add(bridge);return g;}
function createGround(c){const g=new THREE.Group();g.add(box(c.outerWidth+8,.12,c.outerDepth+8,mat(GRASS,.98),0,-.04,0));const road=box(c.bridgeWidth*.72,.035,c.outerDepth+6,mat(PATH,.98),0,.09,2.6);g.add(road);return g;}
function createTrees(c,rand){const g=new THREE.Group(),tr=mat('#4c3b2b',1),leaf=mat('#2f5a38',.98);const n=Math.round(c.forestDensity*80);for(let i=0;i<n;i++){const ang=rand()*Math.PI*2,r=(Math.max(c.outerWidth,c.outerDepth)*.7)+rand()*6;const x=Math.cos(ang)*r,z=Math.sin(ang)*r;if(Math.abs(x)<1.6&&z>0)continue;g.add(cyl(.09,.7,tr,x,.35,z,7));const crown=new THREE.Mesh(new THREE.ConeGeometry(.42+.18*rand(),1.0+rand()*.55,8),leaf);crown.position.set(x,1.1,z);g.add(crown);}return g;}
function createGarden(c,rand){const g=new THREE.Group();if(!c.garden)return g;const x=-c.outerWidth*.27,z=-c.outerDepth*.24;g.add(box(2.5,.04,1.7,mat('#536743',.98),x,.09,z));for(let i=0;i<14;i++){const px=x+(rand()-.5)*2.2,pz=z+(rand()-.5)*1.4,flower=cyl(.025,.12,mat('#42613b',1),px,.16,pz,6);g.add(flower);g.add(cyl(.055,.055,mat(FLOWER[i%FLOWER.length],.8),px,.245,pz,8));}return g;}
function createVillage(c,rand){const g=new THREE.Group();if(!c.village)return g;const plaster=mat('#9a876b',.95),roof=mat(ROOF,.95);for(let i=0;i<c.villageHouses;i++){const side=i%2?1:-1,x=side*(c.outerWidth/2+1.8+rand()*2.4),z=(rand()-.5)*(c.outerDepth+3);const house=new THREE.Group();house.position.set(x,0,z);house.add(box(.8,.7,.65,plaster,0,.35,0));const r=new THREE.Mesh(new THREE.ConeGeometry(.63,.42,4),roof);r.position.y=.9;r.rotation.y=Math.PI/4;house.add(r);g.add(house);}return g;}
export function generateCastle(c){const root=new THREE.Group();root.name='ProceduralCastle';const rand=mulberry32(c.seed??731942);root.add(createGround(c));root.add(createMoat(c));root.add(createWalls(c));root.add(createKeep(c));root.add(createGarden(c,rand));root.add(createTrees(c,rand));root.add(createVillage(c,rand));if(c.innerCourtyard){const well=cyl(.35,.32,mat(STONE_DARK,.96),1.8,.16,-1.1,12);root.add(well);}root.userData.stats={mode:'procedural-castle-v1',style:c.style,walls:4,towers:8,moat:!!c.moat,bridge:!!c.moat,garden:!!c.garden,forestTrees:Math.round(c.forestDensity*80),villageHouses:c.village?c.villageHouses:0,outerWidth:c.outerWidth,outerDepth:c.outerDepth};return root;}
