import * as THREE from 'three';
import { mulberry32 } from '../core/state.js';

const mat=(color,roughness=.82,metalness=.04,extra={})=>new THREE.MeshStandardMaterial({color,roughness,metalness,...extra});
const WHITE='#d8dde3', DARK='#171b22', BASE='#262d36', FLOOR='#d9dde2';
const PRODUCT_COLORS=['#e23d3d','#f2b632','#2d8bd7','#41a85f','#f06c35','#8b5fc7','#df4f9a','#2eb3a8','#e8e8e8','#5d6672'];
const box=(w,h,d,m,x=0,y=0,z=0,shadow=true)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=shadow;o.receiveShadow=shadow;return o;};

function normalizePlan(c,naturalW,naturalDepth){
  const p=c.plan??{};
  const cellSize=Math.max(.4,Math.min(10,Number(p.cellSize??1.5)));
  const cols=Math.max(4,Math.min(160,Math.round(p.cols??Math.ceil(naturalW/cellSize))));
  const rows=Math.max(4,Math.min(160,Math.round(p.rows??Math.ceil(naturalDepth/cellSize))));
  const activeSet=new Set(Array.isArray(p.activeCells)?p.activeCells:[]),custom=activeSet.size>0;
  const isActive=(r,col)=>custom?activeSet.has(`${r},${col}`):true;
  return {cellSize,cols,rows,isActive,activeSet,custom,dividers:new Set(Array.isArray(p.dividers)?p.dividers:[]),sectors:Array.isArray(p.sectors)?p.sectors:[],showWalls:p.showWalls!==false,wallHeight:Math.max(.8,Math.min(5,Number(p.wallHeight??2.8))),wallThickness:Math.max(.05,Math.min(.35,Number(p.wallThickness??.12))),objectPlacements:p.objectPlacements&&typeof p.objectPlacements==='object'?p.objectPlacements:{}};
}
function worldToCell(plan,x,z){const ox=-plan.cols*plan.cellSize/2,oz=-plan.rows*plan.cellSize/2;return {c:Math.floor((x-ox)/plan.cellSize),r:Math.floor((z-oz)/plan.cellSize)};}
function cellActive(plan,r,c){return r>=0&&r<plan.rows&&c>=0&&c<plan.cols&&plan.isActive(r,c);}
function footprintFits(plan,x,z,w,d,rotation=0,margin=.08){const rot=Math.abs(Math.sin(rotation))>.7,fw=rot?d:w,fd=rot?w:d,pts=[[x-fw/2-margin,z-fd/2-margin],[x+fw/2+margin,z-fd/2-margin],[x-fw/2-margin,z+fd/2+margin],[x+fw/2+margin,z+fd/2+margin],[x,z]];return pts.every(([px,pz])=>{const q=worldToCell(plan,px,pz);return cellActive(plan,q.r,q.c);});}
function nearestValid(plan,desired,w,d,rotation=0){if(footprintFits(plan,desired.x,desired.z,w,d,rotation))return desired;const q=worldToCell(plan,desired.x,desired.z),max=Math.max(plan.rows,plan.cols);for(let rad=0;rad<max;rad++)for(let rr=q.r-rad;rr<=q.r+rad;rr++)for(let cc=q.c-rad;cc<=q.c+rad;cc++){if(!cellActive(plan,rr,cc))continue;const x=-plan.cols*plan.cellSize/2+(cc+.5)*plan.cellSize,z=-plan.rows*plan.cellSize/2+(rr+.5)*plan.cellSize;if(footprintFits(plan,x,z,w,d,rotation))return {x,z};}return null;}

export function computeSupermarketLayout(c){
  const gondolaRows=Math.max(1,Math.round(c.gondolaRows??5)),modules=Math.max(1,Math.round(c.modules??8)),shelves=Math.max(1,Math.round(c.shelves??5));
  const moduleWidth=c.moduleWidth??1,depth=c.depth??.78,height=c.height??1.8,aisleWidth=c.aisleWidth??1.75;
  const naturalW=modules*moduleWidth+4.2,naturalDepth=Math.max(8,gondolaRows*depth+(gondolaRows-1)*aisleWidth+5.6),plan=normalizePlan(c,naturalW,naturalDepth);
  const width=plan.cols*plan.cellSize,storeDepth=plan.rows*plan.cellSize,objects=[],custom=plan.objectPlacements,rowPitch=depth+aisleWidth,rowStart=-(gondolaRows-1)*rowPitch/2;
  for(let r=0;r<gondolaRows;r++){let usedModules=modules,placed=null,id=`gondola-${r}`;while(usedModules>0&&!placed){const w=usedModules*moduleWidth+(c.endcaps!==false?depth*.68:0),base=custom[id]??{x:0,z:rowStart+r*rowPitch,rotation:0},pos=nearestValid(plan,base,w,depth,base.rotation??0);if(pos)placed={id,type:'gondola',row:r,x:pos.x,z:pos.z,rotation:base.rotation??0,width:w,depth,modules:usedModules};else usedModules--;}if(placed)objects.push(placed);}
  if(c.wallGondolas!==false){for(const side of[-1,1]){const id=`wall-${side<0?'north':'south'}`,w=modules*moduleWidth,d=depth*.82,base=custom[id]??{x:0,z:side*(storeDepth/2-plan.cellSize*.65),rotation:0},pos=nearestValid(plan,base,w,d,base.rotation??0);if(pos)objects.push({id,type:'wall',side,x:pos.x,z:pos.z,rotation:base.rotation??0,width:w,depth:d,modules});}}
  const promo=Math.max(0,Math.min(20,Math.round(c.promoTables??2)));for(let i=0;i<promo;i++){const id=`promo-${i}`,base=custom[id]??{x:-width*.25+i*(width*.5/Math.max(1,promo-1)),z:-storeDepth*.32,rotation:0},pos=nearestValid(plan,base,1.35,.85,base.rotation??0);if(pos)objects.push({id,type:'promo',x:pos.x,z:pos.z,rotation:base.rotation??0,width:1.35,depth:.85});}
  const checkouts=Math.max(0,Math.min(30,Math.round(c.checkouts??4)));for(let i=0;i<checkouts;i++){const id=`checkout-${i}`,base=custom[id]??{x:-width*.3+i*(width*.6/Math.max(1,checkouts-1)),z:storeDepth*.32,rotation:Math.PI/2},pos=nearestValid(plan,base,1.9,.75,base.rotation??Math.PI/2);if(pos)objects.push({id,type:'checkout',index:i,x:pos.x,z:pos.z,rotation:base.rotation??Math.PI/2,width:1.9,depth:.75});}
  return {plan,width,depth:storeDepth,rows:gondolaRows,modules,shelves,moduleWidth,gondolaDepth:depth,height,aisleWidth,objects};
}

function addProducts(g,rand,width,depth,y,side,fill=.78){const count=Math.max(2,Math.floor(width/.2)),z=side*(depth*.50+.035);for(let i=0;i<count;i++){if(rand()>fill)continue;const w=Math.min(.14,width/count*.72),h=.18+rand()*.18,d=.10+rand()*.05,x=-width/2+(i+.5)*(width/count),m=mat(PRODUCT_COLORS[Math.floor(rand()*PRODUCT_COLORS.length)],.72);let p;if(rand()<.18){p=new THREE.Mesh(new THREE.CylinderGeometry(w*.35,w*.35,h,8),m);p.position.set(x,y+h/2,z);}else p=box(w,h,d,m,x,y+h/2,z,false);p.castShadow=false;p.receiveShadow=false;g.add(p);}}
function createModule(c,rand){const g=new THREE.Group(),w=c.moduleWidth,d=c.depth,h=c.height,shelves=c.shelves,frame=mat(DARK,.66,.20),shelf=mat(WHITE,.76,.06),back=mat('#b9c1ca',.88),base=mat(BASE,.86);g.add(box(w,.12,d,base,0,.06,0),box(w,.035,.035,frame,0,h-.04,0));for(const sx of[-1,1])g.add(box(.045,h,.045,frame,sx*(w/2-.025),h/2,0));if(c.backPanel)g.add(box(w*.98,h*.92,.035,back,0,h*.49,0));const step=(h-.28)/Math.max(1,shelves);for(let s=0;s<shelves;s++){const y=.18+s*step;g.add(box(w*.96,.035,d*.92,shelf,0,y,0));addProducts(g,rand,w*.90,d*.42,y+.025,1,c.productFill);if(c.doubleSided)addProducts(g,rand,w*.90,d*.42,y+.025,-1,c.productFill);}return g;}
function createGondola(c,rowIndex,usedModules){const g=new THREE.Group(),rand=mulberry32((c.seed??246810)+rowIndex*104729),total=usedModules*c.moduleWidth;for(let m=0;m<usedModules;m++){const mod=createModule(c,rand);mod.position.x=-total/2+(m+.5)*c.moduleWidth;g.add(mod);}if(c.endcaps!==false)for(const side of[-1,1]){const end=createModule({...c,moduleWidth:c.depth*1.25,depth:c.moduleWidth*.72,doubleSided:false,backPanel:true},rand);end.rotation.y=Math.PI/2;end.position.x=side*(total/2+c.depth*.34);g.add(end);}return g;}
function createWallRun(c,usedModules){const g=new THREE.Group(),rand=mulberry32((c.seed??246810)+7717),total=usedModules*c.moduleWidth;for(let m=0;m<usedModules;m++){const mod=createModule({...c,doubleSided:false,depth:c.depth*.82},rand);mod.position.x=-total/2+(m+.5)*c.moduleWidth;g.add(mod);}return g;}
function createPromoTable(rand){const g=new THREE.Group(),base=mat('#b8bdc5',.78,.08),trim=mat(DARK,.7,.16);g.add(box(1.25,.65,.75,base,0,.34,0),box(1.31,.06,.81,trim,0,.69,0));for(let i=0;i<8;i++)g.add(box(.15,.18+rand()*.13,.12,mat(PRODUCT_COLORS[Math.floor(rand()*PRODUCT_COLORS.length)],.76),(rand()-.5)*1.0,.82,(rand()-.5)*.56,false));return g;}
function createCheckout(index){const g=new THREE.Group(),body=mat('#2c333c',.74,.15),top=mat('#d9dde2',.55,.08),screen=mat('#101820',.28,.25);g.add(box(1.75,.78,.62,body,0,.39,0),box(1.86,.08,.68,top,0,.82,0),box(.30,.32,.08,screen,.42,1.05,-.15),box(.42,.08,.28,top,-.52,.91,.10));g.userData.checkout=index+1;return g;}
function buildPlan(root,layout){const p=layout.plan,floorMat=mat(FLOOR,.94),wallMat=mat('#dfe5ea',.88,.02),dividerMat=mat('#cbd3da',.84,.03),originX=-p.cols*p.cellSize/2,originZ=-p.rows*p.cellSize/2,sectorByCell=new Map();for(const s of p.sectors)for(const key of s.cells??[])sectorByCell.set(key,s);let floorCells=0,wallSegments=0,dividerSegments=0;const active=(r,c)=>cellActive(p,r,c);for(let r=0;r<p.rows;r++)for(let c=0;c<p.cols;c++){if(!active(r,c))continue;floorCells++;const x=originX+(c+.5)*p.cellSize,z=originZ+(r+.5)*p.cellSize,sector=sectorByCell.get(`${r},${c}`),fm=sector?mat(sector.color||FLOOR,.94):floorMat;root.add(box(p.cellSize*.995,.05,p.cellSize*.995,fm,x,.02,z,false));if(p.showWalls){if(!active(r-1,c)){root.add(box(p.cellSize+p.wallThickness,p.wallHeight,p.wallThickness,wallMat,x,p.wallHeight/2,z-p.cellSize/2));wallSegments++;}if(!active(r+1,c)){root.add(box(p.cellSize+p.wallThickness,p.wallHeight,p.wallThickness,wallMat,x,p.wallHeight/2,z+p.cellSize/2));wallSegments++;}if(!active(r,c-1)){root.add(box(p.wallThickness,p.wallHeight,p.cellSize+p.wallThickness,wallMat,x-p.cellSize/2,p.wallHeight/2,z));wallSegments++;}if(!active(r,c+1)){root.add(box(p.wallThickness,p.wallHeight,p.cellSize+p.wallThickness,wallMat,x+p.cellSize/2,p.wallHeight/2,z));wallSegments++;}if(p.dividers.has(`${r},${c},h`)){root.add(box(p.cellSize*.92,p.wallHeight,p.wallThickness,dividerMat,x,p.wallHeight/2,z));dividerSegments++;}if(p.dividers.has(`${r},${c},v`)){root.add(box(p.wallThickness,p.wallHeight,p.cellSize*.92,dividerMat,x,p.wallHeight/2,z));dividerSegments++;}}}return {floorCells,wallSegments,dividerSegments};}

export function generateSupermarket(c){const root=new THREE.Group();root.name='ProceduralSupermarket';const layout=computeSupermarketLayout(c),planStats=buildPlan(root,layout),cfg={...c,rows:layout.rows,modules:layout.modules,shelves:layout.shelves,moduleWidth:layout.moduleWidth,depth:layout.gondolaDepth,height:layout.height,aisleWidth:layout.aisleWidth,storeDepth:layout.depth},rand=mulberry32(c.seed??246810);let endcaps=0,actualModules=0,wallRuns=0,promo=0,checkouts=0;for(const o of layout.objects){let obj=null;if(o.type==='gondola'){obj=createGondola(cfg,o.row,o.modules);actualModules+=o.modules;endcaps+=c.endcaps===false?0:2;}else if(o.type==='wall'){obj=createWallRun(cfg,o.modules);wallRuns++;}else if(o.type==='promo'){obj=createPromoTable(rand);promo++;}else if(o.type==='checkout'){obj=createCheckout(o.index);checkouts++;}if(!obj)continue;obj.position.set(o.x,0,o.z);obj.rotation.y=o.rotation||0;obj.userData.layoutId=o.id;root.add(obj);}root.userData.layout=layout;root.userData.stats={mode:'procedural-supermarket-v5',rows:layout.objects.filter(o=>o.type==='gondola').length,modules:layout.modules,shelves:layout.shelves,gondolaModules:actualModules,endcaps,wallRuns,promoTables:promo,checkouts,width:layout.width,depth:layout.depth,aisles:Math.max(1,layout.rows-1),floorCells:planStats.floorCells,wallSegments:planStats.wallSegments,dividerSegments:planStats.dividerSegments,wallsVisible:layout.plan.showWalls};return root;}
